version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=dmusic
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    volumes:
      - .:/var/www
    networks:
      - dmusic-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dmusic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dmusic-network

volumes:
  postgres_data:

networks:
  dmusic-network:
    driver: bridge
